namePrefix: capv-

namespace: capi-webhook-system

commonLabels:
  cluster.x-k8s.io/provider: "infrastructure-vsphere"

bases:
- ../../../config/crd
- ../../../config/webhook
- ../../../config/manager
- ../../../config/certmanager

patchesStrategicMerge:
  - ../../../config/default/manager_image_patch.yaml
  - ../../../config/default/manager_pull_policy.yaml
  - ../../../config/default/manager_webhook_patch.yaml
  - ../../../config/default/webhookcainjection_patch.yaml

vars:
  - name: CERTIFICATE_NAMESPACE # namespace of the certificate CR
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: serving-cert # this name should match the one in certificate.yaml
    fieldref:
      fieldpath: metadata.namespace
  - name: CERTIFICATE_NAME
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1
      name: serving-cert # this name should match the one in certificate.yaml
  - name: SERVICE_NAMESPACE # namespace of the service
    objref:
      kind: Service
      version: v1
      name: webhook-service
    fieldref:
      fieldpath: metadata.namespace
  - name: SERVICE_NAME
    objref:
      kind: Service
      version: v1
      name: webhook-service

configurations:
  - ../../../config/default/kustomizeconfig.yaml

patchesJson6902:
  - target: # NOTE: This patch needs to be repeatd for EACH CustomResourceDefinition you have under crd/bases.
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: vsphereclusters.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target: # NOTE: This patch needs to be repeatd for EACH CustomResourceDefinition you have under crd/bases.
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: vsphereclustertemplates.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target: # NOTE: This patch needs to be repeatd for EACH CustomResourceDefinition you have under crd/bases.
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: vspherefailuredomains.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target: # NOTE: This patch needs to be repeatd for EACH CustomResourceDefinition you have under crd/bases.
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: vspheredeploymentzones.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target: # NOTE: This patch needs to be repeatd for EACH CustomResourceDefinition you have under crd/bases.
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: vsphereclustertemplates.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target: # NOTE: This patch needs to be repeatd for EACH CustomResourceDefinition you have under crd/bases.
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: vspheremachines.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target: # NOTE: This patch needs to be repeatd for EACH CustomResourceDefinition you have under crd/bases.
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: vspheremachinetemplates.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
  - target: # NOTE: This patch needs to be repeatd for EACH CustomResourceDefinition you have under crd/bases.
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: vspherevms.infrastructure.cluster.x-k8s.io
    path: patch_crd_webhook_namespace.yaml
